# Generated by Django 3.2.18 on 2023-04-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(default='jump-float'),
            preserve_default=False,
        ),
    ]
